config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
after_create :send_notification

def send_notification
  voice_token = '445955416e566d51474f7674576c756768494e787a6c4d535870736a5147636a4661467855544c6e4d474366'
  @result = HTTParty.get("https://api.tropo.com/1.0/sessions?action=create&token=#{voice_token}&numberToDial=" + User.find(self.assigned_to_user_id).mobile_number + '&ticketNumber=' + self.id.to_s)
end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :submitted_by_user_id, :assigned_to_user_id, :reported_by, :spark_room_id, :contact_info_phone, :contact_info_email, :notes)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :submitted_by_user_id %><br>
    <%= collection_select(:ticket, :submitted_by_user_id, User.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :assigned_to_user_id %><br>
    <%= collection_select(:ticket, :assigned_to_user_id , User.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :reported_by %><br>
    <%= f.text_field :reported_by %>
  </div>
  <div class="field">
    <%= f.label :spark_room_id %><br>
    <%= f.text_field :spark_room_id %>
  </div>
  <div class="field">
    <%= f.label :contact_info_phone %><br>
    <%= f.text_field :contact_info_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_info_email %><br>
    <%= f.text_field :contact_info_email %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Submitted by user</th>
      <th>Assigned to user</th>
      <th>Reported by</th>
      <th>Spark room</th>
      <th>Contact info phone</th>
      <th>Contact info email</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.submitted_by_user_id %></td>
        <td><%= ticket.assigned_to_user_id %></td>
        <td><%= ticket.reported_by %></td>
        <td><%= ticket.spark_room_id %></td>
        <td><%= ticket.contact_info_phone %></td>
        <td><%= ticket.contact_info_email %></td>
        <td><%= ticket.notes %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Submitted by user:</strong>
  <%= @ticket.submitted_by_user_id %>
</p>

<p>
  <strong>Assigned to user:</strong>
  <%= @ticket.assigned_to_user_id %>
</p>

<p>
  <strong>Reported by:</strong>
  <%= @ticket.reported_by %>
</p>

<p>
  <strong>Spark room:</strong>
  <%= @ticket.spark_room_id %>
</p>

<p>
  <strong>Contact info phone:</strong>
  <%= @ticket.contact_info_phone %>
</p>

<p>
  <strong>Contact info email:</strong>
  <%= @ticket.contact_info_email %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @ticket.notes %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>